### ISSUE TITLE
error

### ISSUE THREAD

**Issue by burakthe06z** [diptampaul/YoutubeViews#2]
/root/YoutubeViews/YoutubeViews.py:26: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
  self.profile=webdriver.FirefoxProfile()
/root/YoutubeViews/YoutubeViews.py:30: DeprecationWarning: firefox_profile has been deprecated, please pass in an Options object
  self.browser=webdriver.Firefox(self.profile)
Traceback (most recent call last):
  File "/root/YoutubeViews/YoutubeViews.py", line 59, in validating
    self.play_video()
  File "/root/YoutubeViews/YoutubeViews.py", line 77, in play_video
    self.browser_setup()
  File "/root/YoutubeViews/YoutubeViews.py", line 30, in browser_setup
    self.browser=webdriver.Firefox(self.profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 1
Aborted

**Comment by bisaimedia** [comment]
bro please can you sort this out. as same error here. please brother
